// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: double_array.proto

#include "double_array.pb.h"
#include "double_array.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace doublearrayservice {

static const char* DoubleArrayService_method_names[] = {
  "/doublearrayservice.DoubleArrayService/SendDoubleArray",
};

std::unique_ptr< DoubleArrayService::Stub> DoubleArrayService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DoubleArrayService::Stub> stub(new DoubleArrayService::Stub(channel, options));
  return stub;
}

DoubleArrayService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendDoubleArray_(DoubleArrayService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DoubleArrayService::Stub::SendDoubleArray(::grpc::ClientContext* context, const ::doublearrayservice::DoubleArrayRequest& request, ::doublearrayservice::CountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::doublearrayservice::DoubleArrayRequest, ::doublearrayservice::CountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDoubleArray_, context, request, response);
}

void DoubleArrayService::Stub::async::SendDoubleArray(::grpc::ClientContext* context, const ::doublearrayservice::DoubleArrayRequest* request, ::doublearrayservice::CountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::doublearrayservice::DoubleArrayRequest, ::doublearrayservice::CountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDoubleArray_, context, request, response, std::move(f));
}

void DoubleArrayService::Stub::async::SendDoubleArray(::grpc::ClientContext* context, const ::doublearrayservice::DoubleArrayRequest* request, ::doublearrayservice::CountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDoubleArray_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::doublearrayservice::CountResponse>* DoubleArrayService::Stub::PrepareAsyncSendDoubleArrayRaw(::grpc::ClientContext* context, const ::doublearrayservice::DoubleArrayRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::doublearrayservice::CountResponse, ::doublearrayservice::DoubleArrayRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDoubleArray_, context, request);
}

::grpc::ClientAsyncResponseReader< ::doublearrayservice::CountResponse>* DoubleArrayService::Stub::AsyncSendDoubleArrayRaw(::grpc::ClientContext* context, const ::doublearrayservice::DoubleArrayRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDoubleArrayRaw(context, request, cq);
  result->StartCall();
  return result;
}

DoubleArrayService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DoubleArrayService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DoubleArrayService::Service, ::doublearrayservice::DoubleArrayRequest, ::doublearrayservice::CountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DoubleArrayService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::doublearrayservice::DoubleArrayRequest* req,
             ::doublearrayservice::CountResponse* resp) {
               return service->SendDoubleArray(ctx, req, resp);
             }, this)));
}

DoubleArrayService::Service::~Service() {
}

::grpc::Status DoubleArrayService::Service::SendDoubleArray(::grpc::ServerContext* context, const ::doublearrayservice::DoubleArrayRequest* request, ::doublearrayservice::CountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace doublearrayservice

