# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import double_array_pb2 as double__array__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in double_array_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DoubleArrayServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDoubleArray = channel.unary_unary(
                '/doublearrayservice.DoubleArrayService/SendDoubleArray',
                request_serializer=double__array__pb2.DoubleArrayRequest.SerializeToString,
                response_deserializer=double__array__pb2.CountResponse.FromString,
                _registered_method=True)


class DoubleArrayServiceServicer(object):
    """Service definition
    """

    def SendDoubleArray(self, request, context):
        """RPC method to send an array of doubles and receive a count
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DoubleArrayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDoubleArray': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDoubleArray,
                    request_deserializer=double__array__pb2.DoubleArrayRequest.FromString,
                    response_serializer=double__array__pb2.CountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doublearrayservice.DoubleArrayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doublearrayservice.DoubleArrayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DoubleArrayService(object):
    """Service definition
    """

    @staticmethod
    def SendDoubleArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doublearrayservice.DoubleArrayService/SendDoubleArray',
            double__array__pb2.DoubleArrayRequest.SerializeToString,
            double__array__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
