# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: double_array.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'double_array.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64ouble_array.proto\x12\x12\x64oublearrayservice\"$\n\x12\x44oubleArrayRequest\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32t\n\x12\x44oubleArrayService\x12^\n\x0fSendDoubleArray\x12&.doublearrayservice.DoubleArrayRequest\x1a!.doublearrayservice.CountResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'double_array_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOUBLEARRAYREQUEST']._serialized_start=42
  _globals['_DOUBLEARRAYREQUEST']._serialized_end=78
  _globals['_COUNTRESPONSE']._serialized_start=80
  _globals['_COUNTRESPONSE']._serialized_end=110
  _globals['_DOUBLEARRAYSERVICE']._serialized_start=112
  _globals['_DOUBLEARRAYSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
